version: '3'

networks:
  jengo_django:

services:
  django:
    build: .
    env_file: .env
    networks:
      - jengo_django
    # Allows running container in dev mode, which loads using bash instead of manage.py
    # Exceptions during development won't require rebuilding the containers
    stdin_open: true
    tty: true
    volumes:
      # For running unit tests
      - .git:/app/.git
      - static:/static
    depends_on:
      - db
  # Intended for local dev
  # Supports multiple database types unlike pgAdmin or phpMyAdmin
  # Possible TODO would be to add this as a configurable option ?
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    networks:
      - jengo_django
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  # Build nginx instead of just running, less sloppy way to generate a self signed cert
  nginx:
    networks:
      - jengo_django
    build: nginx
    env_file: .env
    ports:
      - "${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}"
    volumes:
      - static:/static
    links:
      - django
    restart: always
  db:
    # Ran into an SSL bug using latest tag, rolling back to 5.7 which works
    # TODO: Troubleshoot
    image: mysql:5.7
    env_file: .env
    networks:
      - jengo_django
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
volumes:
  mysql_data:
  static:
