# Sample of a specific environment
rev: 4

redis:
  cluster:
    enabled: false

helm-django:
  replicas: 2
  revisionHistoryLimit: 2
  env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: SECRET_KEY
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: DATABASE_URL
    - name: DB_ENGINE
      value: django.db.backends.postgresql
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: jolene-test1
          key: host
